package model;

public class BankAccount {
	private int id;
	private String iban;
	private double balance;
	private boolean active;
	
	private static int counter = 1;

	
// getters
	public int getId() {
		return id;
	}
	public String getIban() {
		return iban;
	}
	public double getBalance() {
		return balance;
	}
	public boolean isActive() {
		return active;
	}
	
	// setters
	// No setter fir id and iban because its auot generated by system.

	public void setBalance(double inputbalance) {
		if (balance >= 0 ) {
			balance = inputbalance;
		}else {
			throw new IllegalArgumentException("NOTE: Balance cannot be empty!");
		}
		
	}
	public void setActive(boolean inputActive) {
		active = inputActive;
	}
	
	// no agrs
	public BankAccount() {
	id = counter++;
	iban = "KJ27 3769 4781 3872 7837";
	setBalance(10000);
	active = true;
	}
	
	//Agrs
	public BankAccount(String iban,double Balance, boolean inputActive) {
		this.id = counter;
		setIban(iban);
		setBalance(Balance);
		setActive(inputActive);
	}
	

	public void setIban(String iban) {
		String ibanString = "[A-Z]{2}[1-9]{2}[ ][1-9]{4}[ ][1-9]{4}[ ][0-9]{4}[ ][0-9]{4}";
		
		if (iban != null && iban.matches(ibanString)) {
			this.iban = iban;
		}
		else {
			throw new IllegalArgumentException("Invalid Iban");
		}
		
	}
	public void deposit(double amount) {
		if (amount <= 0) {
			throw new IllegalArgumentException("NOTE:Amount cannot be empty!");
		}
		balance += amount;
	}
	public boolean withdraw(double inputAmount) {
		if (inputAmount <=0) {
			throw new IllegalArgumentException("NOTE:Amount cannot be negative!");
		}
		if (balance >= inputAmount) {
			balance -= inputAmount;
			return true;
		}
		return false;
	}
	
	//String tostring
	public String toString() {
	String result = id + " " + iban + " EUR " + balance + " " + active;
	return result;
	}
}
